---
title: "bossr"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{bossr}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

Install the companion package to follow along the vignette: `install.packages('bossrdata', repos = 'https://pennsive.github.io/drat', type='source')`

```{r setup}
library(bossr)
library(bossrdata)
data(oligo)
n.cores = 4
```

```{r betamix.img}
system.time(thr <- betamix.img(oligo, n.cores = 4))
```

```{r, include=FALSE}}
# TODO: Delete this chunk once testing is successful
saveRDS(thr, here::here('tmp/thr.rds'))
hist(thr)
```

```{r threshold}
system.time(mask <- threshold.img(oligo, thr, n.cores = 4))
```

```{r, include=FALSE}
# TODO: Delete this chunk once testing is successful
saveRDS(mask, here::here('tmp/mask.rds'))
mask |> as.vector() |> table()
```

```{r median_filtering}
system.time(mask_filtered <- bossr::median.filtering(mask))
```

```{r, include=FALSE}
saveRDS(mask_filtered, here::here('tmp/mask_filtered.rds'))
mask_filtered |> as.vector() |> table()
```

```{r connect_components}
system.time(labels <- bossr::connect.components(mask_filtered))
```

```{r, include=FALSE}
saveRDS(labels, here::here('tmp/labels.rds'))

```


```{r cell_df}
cell_df <- bossr::track.components(labels)
```


```{r cell_df}
bossr::get.delta.n(cell_df)
```

```{r annot_dat}
annotate.df(cell_df, t = 1)
```