---
title: "bossr"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Install the companion package to follow along the vignette: `install.packages('bossrdata', repos = 'https://pennsive.github.io/drat', type='source')`

```{r setup}
library(bossr)
library(bossrdata)
data(oligo)
n.cores = 4
```

```{r betamix.img}
system.time(thr <- bossr::betamix.img(oligo, n.cores = 4))
```

```{r, include=FALSE}}
# TODO: Delete this chunk once testing is successful
saveRDS(thr, here::here('tmp/thr.rds'))
hist(thr)
```

```{r threshold}
system.time(mask <- bossr::threshold.img(oligo, thr, n.cores = 4))
```

```{r, include=FALSE}
# TODO: Delete this chunk once testing is successful
saveRDS(mask, here::here('tmp/mask.rds'))
mask |> as.vector() |> table()
```

```{r median_filtering}
system.time(mask_filtered <- bossr::median.filtering(mask))
```

```{r, include=FALSE}
saveRDS(mask_filtered, here::here('tmp/mask_filtered.rds'))
mask_filtered |> as.vector() |> table()
```

```{r connect_components}
system.time(labels <- bossr::connect.components(mask_filtered))
```
```{r}
labels |> c() |> unique()
```

```{r, include=FALSE}
saveRDS(labels, here::here('tmp/labels.rds'))
```


```{r cell_df}
# TODO: fix
# each index should appear on at least two t, no?
cell_df <- bossr::track.components(labels)
```


```{r cell_df}
# TODO: make this one function that returns a summary
# TODO: change name of function
bossr::get.delta.n(cell_df)
```

```{r}
bossr::post.process.df(cell_df, t = 4)
```

```{r annot_dat}
# set up env
temp_env = new.env()
attach(temp_env)
# params
df = cell_df
t = 1
#annotate.df <- function(df, t){
    index <- sort(unique(df$index))
  
    result.index <- c()
    # 
    i = index[1]
    #
    for(i in index){
      index.X <- df[which(df$index==i),"x"]
      index.Y <- df[which(df$index==i),"y"]
      index.Z <- df[which(df$index==i),"z"]

      new.df <- df |> 
        dplyr::filter(x <= max(index.X)+30 & x>= min(index.X)-30) |> 
        dplyr::filter(y <= max(index.Y)+30 & y >= min(index.Y)-30) |>
        dplyr::filter(z <= max(index.Z)+5 & z >= min(index.Z)-5) 
      
      if(length(unique(new.df$index)) > 1 && length(unique(new.df$t)) == nrow(new.df)){
        
        index.t <- c()
        for(j in unique(new.df$index)){
          index.t <- c(index.t, df[which(df$index == j),"t"])
        }

        if(length(index.t) == length(unique(index.t))){
          result.index<- rbind(result.index, sort(unique(new.df$index)))}
        

      }
    }

    result.index <- result.index[which(duplicated(result.index)==FALSE),]
    if (!is.null(result.index))}
      for(i in seq_len(result.index)){
      
        df$index[which(df$index==result.index[i,2])] <- result.index[i,1]
      }
    }
   
    return(df)
}


```

```{r}
# plotting
```
